### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DennisMarcus** [jornoS/javascriptopdrachten#1]
Homeadres.html
Look at your class names and try to be more specific and use logical names (for example i would name userdiv => userList and user => item)

Body margin
Header buttons missing border
Userdiv, user need some rework (image left name right of the image)
Add some space between user div's
Last user div partialy hidden because of workbar (fix with margin bottom on userdiv)
Images could be a little bit bigger
Try to make the modal more appealing, a simple border and some positioning should do the trick
Also see if you can make a more clear way of closing the modal (back button)

Sass:
Try to leave some blank lines between blocks, that way the code will look cleaner
Also take a look at sass variables for colors i see #FFFFFF returning multiple times

JS:
Take a look at your indenting, try to make everything align nicely and watch your empty lines
Also try to be consistent in your variable names for example you use camel case with infoDiv but only use lowercase with fullname

**Comment by jornoS** [comment]
i did all the feedback
